Repository jwplayer/jwplayer, pull requests merged in 2018-05, with the labels that each got.

#2879 Set "mediaType" to audio when mimeType is "audio/mp4"
  src/js/providers/default.js
Labels: bug, needs-review

#2856 Add Padding to Display Icons While Casting
  src/css/controls/imports/display.less
Labels: needs-review

#2863 Idle button variant with "Play" label
  src/css/controls/imports/idle-variants.less
  src/js/view/controls/play-display-icon.js
  test/unit/play-display-icon-test.js
Labels: needs-review

#2881 Ajax Error Codes
  src/js/utils/ajax.js
  src/js/utils/helpers.js
  src/js/utils/parser.js
  test/unit/ajax-test.js
Labels: needs-review

#2886 Use underscore to filter the textTracks array-like object
  src/js/providers/tracks-mixin.js
Labels: bug

#2893 Only allow one plugin loader per api/model instance
  src/js/api/Setup.js
  src/js/api/core-shim.js
  src/js/plugins/loader.js
  src/js/plugins/plugins.js
Labels: needs-review

#2891 Use title casing for "About this video"
  src/js/api/config.js
Labels: needs-review

#2889 Convert vars to let/consts
  .eslintrc
  src/js/compatibility.js
  src/js/controller/instream-adapter.js
  src/js/controller/model.js
  src/js/controller/tracks-helper.js
  src/js/controller/tracks-loader.js
  src/js/events/change-state-event.js
  src/js/parsers/captions/dfxp.js
  src/js/parsers/captions/srt.js
  src/js/parsers/captions/vttparser.js
  src/js/parsers/mediaparser.js
  src/js/playlist/item.js
  src/js/playlist/loader.js
  src/js/plugins/plugin.js
  src/js/polyfills/vttregion.js
  src/js/polyfills/webvtt.js
  src/js/providers/html5.js
  src/js/providers/providers-register.js
  src/js/providers/tracks-mixin.js
  src/js/providers/video-listener-mixin.js
  src/js/utils/backbone.events.js
  src/js/utils/browser.js
  src/js/utils/css.js
  src/js/utils/defaults.js
  src/js/utils/dom.js
  src/js/utils/strings.js
  src/js/utils/underscore.js
  src/js/utils/validator.js
  src/js/view/controls/.eslintrc
  src/js/view/controls/components/thumbnails.mixin.js
  src/js/view/controls/components/timeslider.js
  src/js/view/logo.js
  src/js/view/preview.js
  src/js/view/title.js
  src/js/view/utils/flag-no-focus.js
  test/unit/captionsrenderer-test.js
  test/unit/css-test.js
  test/unit/dfxp-test.js
  test/unit/dom-test.js
  test/unit/events-middleware-test.js
  test/unit/helpers-test.js
  test/unit/language-test.js
  test/unit/parser-test.js
  test/unit/playlist-item-test.js
  test/unit/playlist-test.js
  test/unit/quality-labels-test.js
  test/unit/rssparser-test.js
  test/unit/skin-test.js
  test/unit/strings-test.js
  test/unit/style-loader-test.js
  test/unit/time-ranges-test.js
  test/unit/timer-test.js
  test/unit/tracks-helper-test.js
Labels: needs-review

#2895 Trigger "visualQuality" from html5 provider with audio streams
  src/js/providers/html5.js
Labels: needs-review

#2898 Set tabindex to -1 on video element
  src/js/program/media-element-pool.js
Labels: bug, needs-review

#2899 Do not submit form when clicking "About This Video"
  src/js/view/controls/templates/rightclick.js
Labels: needs-review

#2859 Populate media notifications with all known video information on Android Chrome
  src/js/controller/controller.js
Labels: enhancement, needs-review

#2900 Use a single matrix transform to resize video in IE/Edge
  src/js/providers/video-actions-mixin.js
Labels: needs-review

#2902 Add Flash errors to export
  src/js/api/errors.js
Labels: enhancement

#2911 Standardize unknown setup errors
  src/js/api/core-shim.js
  src/js/api/errors.js
  test/unit/core-shim-test.js
Labels: enhancement

#2897 Set fullscreen on change event for screen.orientation
  src/js/view/utils/views-manager.js
Labels: enhancement, needs-review

#2915 Set player element role to "application"
  src/templates/player.js
Labels: needs-review

#2919 Improve keyboard accessibility in settings menu
  src/js/utils/dom.js
  src/js/view/controls/components/settings/menu.js
  src/js/view/controls/components/settings/submenu.js
  src/js/view/controls/controls.js
Labels: bug, enhancement, needs-review

#2932 Flatten error events
  src/js/api/core-shim.js
  src/js/program/program-controller.js
Labels: bug

#2931 Implement html5 standard errors
  src/js/providers/html5.js
  src/js/providers/video-listener-mixin.js
Labels: enhancement

#2936 Avoid appending generic Playlist error copy to all playlist errors
  src/js/controller/controller.js
  src/js/playlist/playlist.js
  test/unit/playlist-filtering-test.js
  test/unit/playlist-test.js
  test/unit/setup-test.js
Labels: bug

#2939 Log errors via static PlayerError method, attach errorEvent listener to core model after initilization
  src/js/api/core-shim.js
  src/js/api/errors.js
  test/unit/errors/player-error-test.js
Labels: bug, needs-review

#2937 Revert timeFormat to fix unlimited build
  src/js/view/controls/controlbar.js
Labels: needs-review

#2938 Route media-controller events through instream during ads mode
  src/js/controller/controller.js
  src/js/controller/instream-adapter.js
  src/js/program/program-controller.js
  src/js/program/program-listeners.js
  test/unit/api-queue-test.js
Labels: needs-review
