Repository jwplayer/jwplayer, pull requests merged in 2018-08, with the labels that each got.

#3011 Create setPlaylistItem method in api
  src/js/api/api.js
  src/js/api/core-shim.js
  src/js/controller/controller.js
  src/js/playlist/playlist.js
  src/js/view/controls/controlbar.js
  src/js/view/controls/nextuptooltip.js
  test/data/api-methods-chainable.js
  test/data/api-methods.js
Labels: enhancement, needs-review

#3017 Assign preload from playlist level to item level
  src/js/controller/controller.js
  src/js/playlist/playlist.js
  test/mock/mock-model.js
  test/unit/playlist-test.js
Labels: bug, needs-review

#3018 Set intersection ratio to the view instead of the model
  src/js/view/utils/views-manager.js
  src/js/view/view.js
Labels: needs-review

#3020 Improve font scaling for captions rendering
  src/js/view/captionsrenderer.js
  src/js/view/view.js
Labels: needs-review

#3024 Default network error message key is "This video file cannot be played."
  src/js/providers/utils/network-error-parser.js
  test/unit/events-middleware-test.js
  test/unit/network-error-parser-test.js
Labels: needs-review

#3023 Fix orientation detection on mobile devices for captions font resizing
  src/js/view/captionsrenderer.js
Labels: needs-review

#3022 Only modify item.starttime when attached equals false
  src/js/program/media-controller.js
  src/js/program/program-controller.js
Labels: bug, needs-review

#3030 Set meta.starttime to playlistitem.starttime
  src/js/controller/controller.js
Labels: bug
