Repository jwplayer/jwplayer, pull requests merged in 2018-06, with the labels that each got.

#2943 Remove flash errors and some flashBlocked handling
  src/css/controls/flags/flash-blocked.less
  src/js/api/errors.js
  src/js/controller/controller.js
  src/js/program/program-listeners.js
  src/js/view/view.js
Labels: needs-review

#2945 Cleanup utils imports
  src/js/controller/tracks-loader.js
  src/js/parsers/jwparser.js
  src/js/parsers/mediaparser.js
  src/js/playlist/loader.js
  src/js/plugins/model.js
  src/js/plugins/plugins.js
  src/js/providers/html5.js
  src/js/providers/video-listener-mixin.js
  src/js/utils/helpers.js
  src/js/utils/log.js
  src/js/utils/math.js
  src/js/view/controls/components/chapters.mixin.js
  src/js/view/controls/components/slider.js
  src/js/view/controls/components/thumbnails.mixin.js
  src/js/view/controls/components/timeslider.js
  src/js/view/controls/controlbar.js
  src/js/view/controls/controls.js
  src/js/view/controls/display-container.js
  src/js/view/controls/nextuptooltip.js
Labels: needs-review

#2944 Make out of bounds HTTP status code consistent
  src/js/providers/utils/network-error-parser.js
  test/unit/network-error-parser-test.js
Labels: needs-review

#2934 Focus on first menu icon on enter
  src/js/view/controls/components/settings/menu.js
Labels: bug

#2946 Output friendly error messages
  src/js/api/Setup.js
  src/js/api/config.js
  src/js/api/core-loader.js
  src/js/api/core-shim.js
  src/js/api/errors.js
  src/js/controller/controller.js
  src/js/playlist/loader.js
  src/js/playlist/playlist.js
  src/js/program/program-controller.js
  src/js/providers/html5.js
  src/js/providers/utils/network-error-parser.js
  src/js/providers/video-listener-mixin.js
  src/js/utils/ajax.js
  src/js/view/error-container.js
  src/templates/error.js
  test/unit/ajax-test.js
  test/unit/playlist-filtering-test.js
  test/unit/playlist-loader-test.js
  test/unit/playlist-test.js
  test/unit/program-controller-test.js
  test/unit/setup-test.js
Labels: needs-review

#2956 Hide time tooltip after scrubbing on mobile
  src/js/view/controls/components/timeslider.js
Labels: needs-review

#2957 Guard against 'handleEvent' exceptions in Edge 15
  src/js/view/controls/rightclick.js
Labels: needs-review

#2921 Maintain cursor after setControls(false), except in fullscreen mode
  src/css/controls/flags/user-inactive.less
Labels: enhancement, needs-review

#2958 Standard errors overlay
  src/css/jwplayer/states.less
  src/js/controller/controller.js
  src/js/view/view.js
  src/templates/error.js
  test/mock/mock-model.js
Labels: bug

#2970 [ADS-1233] Set itemReady when ad is playing.
  src/js/program/program-controller.js
Labels: needs-review

#2983 Plugins with the same name should only load and be registered once
  src/js/plugins/loader.js
  src/js/plugins/model.js
  src/js/plugins/plugin.js
  test/files/plugin1.js
  test/files/plugin2.js
  test/unit/plugins-test.js
  test/unit/setup-test.js
Labels: needs-review
