Repository jwplayer/jwplayer, pull requests merged in 2018-02, with the labels that each got.

#2720 ESLint clean up
  .eslintrc
  Gruntfile.js
  package.json
  src/js/api/api.js
  src/js/api/timer.js
  src/js/controller/captions.js
  src/js/controller/controller.js
  src/js/controller/instream-adapter.js
  src/js/jwplayer.js
  src/js/parsers/captions/srt.js
  src/js/plugins/model.js
  src/js/polyfills/promise.js
  src/js/program/program-controller.js
  src/js/providers/providers.js
  src/js/utils/browser.js
  src/js/utils/parser.js
  src/js/utils/playerutils.js
  src/js/utils/validator.js
  src/js/view/captionsrenderer.js
  src/js/view/view.js
  test/.eslintrc
  test/data/aac.js
  test/data/api-methods-chainable.js
  test/data/flv.js
  test/data/mp4.js
  test/unit/api-test.js
  test/unit/background-loading-test.js
  test/unit/css-test.js
  test/unit/jwplayer-selectplayer-test.js
  test/unit/media-pool-tests.js
  test/unit/model-qoe-test.js
  test/unit/program-controller-test.js
  test/unit/scriptloader-test.js
Labels: needs-review

#2718 Default writingMode to display horizontal text
  src/js/polyfills/webvtt.js
Labels: needs-review

#2716 Changed Default Localization for Live to 'Live'
  src/js/api/config.js
Labels: needs-review

#2719 Prevent idle state over ads while background loading providers
  src/js/view/view-model.js
  test/unit/view-model.js
Labels: needs-review

#2705 Deprecate Discover Icon & Localization
  src/js/api/config.js
Labels: needs-review

#2724 Keep instream model volume and mute in sync with the player
  src/js/program/ad-program-controller.js
Labels: needs-review

#2729 Fix instream autoplay muted on iOS and Android
  src/js/program/ad-program-controller.js
Labels: needs-review

#2730 Add aria-label for the Live Button
  src/js/view/controls/controlbar.js
Labels: needs-review

#2731 Unmute instream pseudo provider when ending autostart muted
  src/js/program/ad-program-controller.js
Labels: needs-review

#2721 Add liveTimeout, a configurable duration to kill a stale live stream
  src/js/api/config.js
  src/js/providers/html5.js
  test/data/model-properties.js
  test/unit/api-config-test.js
Labels: docs-this, enhancement, needs-review

#2727 Add new method for DAI to enable time slider
  src/js/controller/instream-adapter.js
Labels: needs-review

#2717 Add canAutoplay test
  src/js/controller/controller.js
  src/js/program/media-element-pool.js
  src/js/program/program-constants.js
  src/js/utils/can-autoplay.js
  test/unit/media-pool-tests.js
Labels: needs-milestone, needs-review

#2733 Align with the left property instead of paddingLeft
  src/js/polyfills/webvtt.js
Labels: needs-review

#2728 Set item.starttime when seek is called before starting
  src/js/controller/controller.js
  src/js/program/media-controller.js
  src/js/program/program-controller.js
Labels: enhancement, needs-review

#2735 Close volume tooltip after tab
  src/js/utils/ui.js
Labels: needs-review

#2736 Add DangerJS
  .travis.yml
  dangerfile.js
  package.json
  yarn.lock
Labels: enhancement, needs-review

#2723 Add getCurrentTime() Public API Method
  docs/api/Api.html
  src/js/api/api.js
  src/js/controller/model.js
  src/js/model/player-model.js
  src/js/program/media-controller.js
  src/js/program/program-listeners.js
  src/js/providers/video-listener-mixin.js
  test/data/api-methods.js
  test/data/model-properties.js
Labels: docs-this, enhancement, needs-review

#2699 Instream adapter listener for suppressed autostart
  src/js/controller/instream-adapter.js
Labels: needs-milestone, needs-review

#2737 Delete unused flowconfig
  src/js/.flowconfig
Labels: tech-debt

#2738 Avoid resetting position & duration in srcReset
  src/js/controller/model.js
  src/js/program/media-controller.js
  test/unit/mediaModel-test.js
Labels: bug, needs-review

#2739 Return the same autoplay Promise...
  src/js/utils/can-autoplay.js
Labels: needs-review

#2743 Adjust autoplay behavior suggestions
  src/js/controller/controller.js
  src/js/utils/can-autoplay.js
Labels: needs-review

#2734 [JW8-1158 ADS-938] Use autoplay test to determine autostart.
  src/js/controller/controller.js
  src/js/controller/model.js
  src/js/events/events.js
  src/js/utils/can-autoplay.js
  src/js/view/controls/controls.js
Labels: needs-review

#2744 Added configuration used in setup() call to model attributes
  src/js/api/api.js
  src/js/api/core-shim.js
  test/data/model-properties.js
Labels: needs-review

#2749 Update autoplay test to v3.0.0.
  src/js/utils/can-autoplay.js
Labels: needs-review

#2750 [JW8-1158 ADS-936] Sync sound settings.
  src/js/controller/controller.js
Labels: needs-review

#2746 Stopped UCBrowser as being detected as Chrome
  src/js/utils/browser.js
Labels: needs-review
