Repository jwplayer/jwplayer, pull requests merged in 2018-03, with the labels that each got.

#2748 Improve mouse handling that shows and hides controls
  src/js/utils/ui.js
  src/js/view/controls/controlbar.js
  src/js/view/controls/controls.js
  src/js/view/utils/clickhandler.js
  src/js/view/view.js
  test/unit/controls-test.js
Labels: needs-review

#2753 Bugfix: Mobile controls toggle regression
  src/js/view/controls/controls.js
  src/js/view/view.js
Labels: needs-review

#2752 IE11 button and tabbing fixes
  src/assets/SVG/arrow.svg
  src/assets/SVG/audio-tracks.svg
  src/assets/SVG/buffer.svg
  src/assets/SVG/captions-off.svg
  src/assets/SVG/captions-on.svg
  src/assets/SVG/close.svg
  src/assets/SVG/fullscreen-not.svg
  src/assets/SVG/fullscreen.svg
  src/assets/SVG/next.svg
  src/assets/SVG/pause.svg
  src/assets/SVG/play.svg
  src/assets/SVG/playback-error.svg
  src/assets/SVG/playback-rate.svg
  src/assets/SVG/quality-100.svg
  src/assets/SVG/quality-25.svg
  src/assets/SVG/quality-50.svg
  src/assets/SVG/quality-75.svg
  src/assets/SVG/replay.svg
  src/assets/SVG/rewind-10.svg
  src/assets/SVG/settings.svg
  src/assets/SVG/stop.svg
  src/assets/SVG/volume-0.svg
  src/assets/SVG/volume-100.svg
  src/assets/SVG/volume-50.svg
  src/js/utils/ui.js
  src/js/view/controls/controls.js
Labels: needs-review

#2756 Replace jQuery hasClass implementation with classList.contains
  src/js/utils/dom.js
Labels: needs-review

#2758 Pause video from autoplay muted on mobile
  src/css/controls/imports/autostartmute.less
Labels: needs-review

#2742 Avoid defaulting item.starttime to 0 in the html5 provider
  src/js/providers/html5.js
Labels: bug, needs-review

#2760 Disable Airplay for Playlists with Dash
  src/js/providers/providers-supported.js
Labels: needs-review

#2759 Add license banner to JS build output
  Gruntfile.js
  jwplayer.license.notice.js
  package-lock.json
  package.json
  src/js/polyfills/promise.js
  src/js/utils/backbone.events.js
  src/js/utils/underscore.js
  webpack.config.js
  yarn.lock
Labels: needs-review

#2761 [JW8-1290] Display autostart unmute button only on touch.
  src/css/controls/flags/ads.less
  src/css/controls/flags/media-audio.less
  src/css/controls/flags/user-inactive.less
  src/css/controls/states.less
  src/js/view/controls/controls.js
Labels: needs-review

#2755 [JW8-1288] Reset autostart cancelable on pause.
  src/js/controller/controller.js
Labels: needs-review

#2765 Fix pause event after restoring background loaded media
  src/js/program/program-controller.js
Labels: bug, needs-review

#2745 Recs Accessibility
  src/js/view/controls/controls.js
Labels: needs-review

#2769 Don't attempt to background load next on last item
  src/js/controller/controller.js
  src/js/program/program-controller.js
Labels: needs-review

#2770 Show controls on iFrame mouseover. Do not show on mouseout.
  src/js/view/view.js
Labels: needs-review

#2762 Background load the next playlist item
  src/js/api/setup-steps.js
  src/js/controller/controller.js
  src/js/controller/model.js
  src/js/playlist/playlist.js
  src/js/program/background-media.js
  src/js/program/media-controller.js
  src/js/program/program-controller.js
  src/js/providers/provider-controller.js
  src/js/providers/providers.js
  test/mock/mock-provider.js
  test/unit/background-loading-test.js
  test/unit/program-controller-test.js
  test/unit/providers-test.js
Labels: enhancement, needs-review

#2771 Background load nextUp item in recs-auto mode
  src/js/controller/controller.js
  src/js/program/background-media.js
  src/js/program/program-controller.js
Labels: needs-review

#2772 Call controller.play in _seek so that it is queued until playback begins
  src/js/controller/controller.js
Labels: bug, needs-review

#2775 Fix background load exceptions crashing playback, background loading of bad nextUp items
  src/js/controller/controller.js
  src/js/playlist/playlist.js
  src/js/program/program-controller.js
Labels: bug, needs-review

#2776 Fix provider loading error handling
  src/js/controller/controller.js
  src/js/providers/providers.js
Labels: needs-review

#2777 Listen to mediaType change on view.init()
  src/js/view/view.js
Labels: bug, needs-review

#2778 Add (is)Object checks to related "nextUp" event and providers.choose
  src/js/controller/controller.js
  src/js/providers/providers.js
Labels: needs-review

#2780 Set posterImage on playlistItem change
  src/js/view/view.js
Labels: bug, needs-review

#2781 When play is triggered by seek, add startTime to meta event to notify plugins
  src/js/controller/controller.js
Labels: needs-review

#2783 Prime on beforePlay even if we will not be interrupting for an ad
  src/js/controller/controller.js
Labels: bug, needs-review

#2782 Avoid background loading DAI items
  src/js/controller/controller.js
Labels: bug, needs-review

#2785 Update player duration on mediaModel change
  src/js/controller/controller.js
Labels: needs-review

#2784 Fire "itemReady" for background loaded items
  src/js/program/program-controller.js
  test/unit/program-controller-test.js
Labels: needs-review

#2787 Add a flag to beforePlay media pool priming so that we do not destroy BGL buffer on subsequent plays
  src/js/controller/controller.js
  src/js/program/program-controller.js
  src/js/program/shared-media-pool.js
Labels: bug, needs-review

#2788 [ADS-1050] Set state to paused after ad.
  src/js/controller/instream-adapter.js
Labels: needs-review

#2786 Shelf crashes when controls are disabled
  src/js/controller/controller.js
  src/js/view/view.js
Labels: needs-review

#2789 Bugfix/beforeplay prime flag
  src/js/controller/controller.js
  src/js/program/program-controller.js
Labels: bug, needs-review

#2790 Delete API plugin instances between player setup
  src/js/api/api.js
  test/unit/api-test.js
Labels: needs-review

#2794 Set item.starttime if seeking from complete
  src/js/program/program-controller.js
Labels: bug, needs-review

#2796 Version 8.2.0
  package.json
Labels: needs-review

#2673 Replace PhantomJS with Headless Chrome
  Gruntfile.js
  karma.conf.js
  package.json
  src/js/providers/html5.js
  src/js/utils/ajax.js
  src/js/utils/browser.js
  test/mock/video-element-polyfill.js
  test/unit/api-get-config-test.js
  test/unit/api-test.js
  test/unit/media-pool-tests.js
  test/unit/setup-test.js
  yarn.lock
Labels: needs-review, unit-tests

#2798 Merge Idle Button A/B Test from v8.2.x into master
  src/css/controls.less
  src/css/controls/imports/idle-variants.less
  src/js/view/controls/play-display-icon.js
  test/unit/play-display-icon-test.js
Labels: needs-review

#2792 Remove "dvrSeekLimit" from Controlbar and Timeslider
  src/js/program/program-listeners.js
  src/js/providers/default.js
  src/js/providers/html5.js
  src/js/providers/video-listener-mixin.js
  src/js/view/controls/components/slider.js
  src/js/view/controls/components/timeslider.js
  src/js/view/controls/controlbar.js
Labels: bug, enhancement, needs-review

#2799 Clear Cues When Changing Playlist Items
  src/js/view/controls/components/timeslider.js
Labels: needs-review

#2801 Move "dvrSeekLimit" to config and model
  src/js/controller/model.js
  src/js/playlist/item.js
  src/js/view/constants.js
  src/js/view/controls/components/timeslider.js
  src/js/view/controls/controlbar.js
  src/js/view/controls/controls.js
Labels: bug, enhancement

#2805 Maintain quality between items & sessions
  src/js/api/config.js
  src/js/api/core-shim.js
  src/js/controller/model.js
  src/js/events/events.js
  src/js/program/program-listeners.js
  src/js/providers/bandwidth-monitor.js
  src/js/providers/default.js
  src/js/utils/underscore.js
  test/data/model-properties.js
  test/unit/program-controller-test.js
Labels: enhancement

#2809 Reset item.starttime to 0 when loading an ad so that replayed ads beg…
  src/js/controller/instream-adapter.js
Labels: bug

#2807 Bugfix/stretching object fit transform
  src/js/providers/html5.js
  src/js/providers/video-actions-mixin.js
  src/js/providers/video-listener-mixin.js
Labels: needs-review

#2811 Disable Related Open & Close API during ads
  src/js/controller/model.js
Labels: needs-review

#2816 Return currentTime in getAlignmentPosition
  src/js/view/captionsrenderer.js
Labels: needs-review
