Repository jwplayer/jwplayer, pull requests merged in 2018-07, with the labels that each got.

#2980 Round playback rates to hundredths instead of quarters
  src/js/api/config.js
  test/unit/api-config-test.js
Labels: needs-review

#2942 Idle button text variants
  src/css/controls/imports/idle-variants.less
  src/js/view/controls/play-display-icon.js
  test/unit/play-display-icon-test.js
Labels: enhancement, needs-review

#2985 Gradient and drop shadow improvements
  package.json
  postcss.config.js
  src/css/controls.less
  src/css/controls/imports/drop-shadow-variants.less
  src/css/shared-imports/vars.less
  src/js/view/view.js
  yarn.lock
Labels: enhancement, needs-review

#2989 Resolve plugin promise when plugins config key is not a url
  src/js/plugins/loader.js
  src/js/plugins/plugin.js
  src/js/plugins/plugins.js
  test/unit/plugins-test.js
Labels: needs-review

#2990 Add jw-reset to Google Chromecast button
  src/js/view/controls/controlbar.js
Labels: bug, needs-review

#2994 Handle non-plugin JavaScript loading via plugins block
  src/js/plugins/model.js
  src/js/plugins/plugin.js
  test/files/noop.js
  test/unit/plugins-test.js
Labels: needs-review

#2993 Merge 8.4.1 into master
  package.json
  postcss.config.js
  src/css/controls.less
  src/css/controls/imports/drop-shadow-variants.less
  src/css/controls/imports/idle-variants.less
  src/css/shared-imports/vars.less
  src/js/plugins/loader.js
  src/js/plugins/model.js
  src/js/plugins/plugin.js
  src/js/plugins/plugins.js
  src/js/program/program-controller.js
  src/js/view/controls/play-display-icon.js
  src/js/view/view.js
  test/files/plugin1.js
  test/files/plugin2.js
  test/unit/play-display-icon-test.js
  test/unit/plugins-test.js
  test/unit/setup-test.js
  yarn.lock
Labels: needs-review

#2991 UI.js refactor
  Gruntfile.js
  karma.conf.js
  src/js/utils/ui.js
  src/js/view/controls/components/settings/content-item.js
  src/js/view/controls/components/slider.js
  src/js/view/controls/components/timeslider.js
  src/js/view/controls/components/volumetooltip.js
  src/js/view/controls/next-display-icon.js
  src/js/view/controls/nextuptooltip.js
  src/js/view/controls/rightclick.js
  src/js/view/logo.js
  src/js/view/utils/clickhandler.js
  test/karma/browserstack-launchers.js
  test/unit/ajax-test.js
  test/unit/jwplayer-selectplayer-test.js
  test/unit/program-controller-test.js
  test/unit/ui-test.js
Labels: needs-review

#2996 Prime video tags on first user-gesture
  src/js/api/core-shim.js
  src/js/controller/controller.js
  src/js/program/media-element-pool.js
  src/js/program/program-controller.js
  src/js/utils/ui.js
Labels: needs-review

#2998 Remove related plugin hooks
  src/js/controller/controller.js
Labels: needs-review

#3002 Add player model "controlsEnabled"
  src/js/model/player-model.js
  src/js/view/controls/controls.js
  test/data/model-properties.js
Labels: needs-review

#3004 Trigger 'remove' when player is reset for plugins
  src/js/api/api.js
  src/js/controller/controller.js
Labels: needs-review

#3008 Only trigger the "remove" event on api instances that have been setup
  src/js/api/api.js
  src/js/api/core-shim.js
  test/unit/api-test.js
  test/unit/controls/settings-menu-test.js
  test/unit/setup-test.js
Labels: needs-review

#3006 Handle Error Completing Setup
  src/js/api/errors.js
  src/js/controller/controller.js
Labels: needs-review

#3010 Generate feedShownId when nextUp appears
  src/js/api/api.js
  src/js/utils/random-id-generator.js
  src/js/view/controls/components/simple-tooltip.js
  src/js/view/controls/controlbar.js
  src/js/view/controls/next-display-icon.js
  src/js/view/controls/nextuptooltip.js
  test/unit/id-generator-test.js
Labels: enhancement, needs-review

#3012 Preload video after first gesture
  src/js/api/core-shim.js
  src/js/controller/controller.js
Labels: needs-review

#3013 Fix captions scaling for iOS devices in fullscreen
  src/js/view/captionsrenderer.js
Labels: needs-review, subtitle-captions

#3014 Set reason as 'File Not Found' when ajax request returns 404
  src/js/controller/captions.js
  src/js/providers/tracks-mixin.js
Labels: bug, needs-review

#3016 Disable nextUp when it's value is set to null in the model
  src/js/view/controls/nextuptooltip.js
Labels: needs-review
