Repository jwplayer/jwplayer, pull requests merged in 2018-04, with the labels that each got.

#2817 Check if the mediaElement was already seeked before seeking on _completeLoad
  src/js/providers/html5.js
Labels: bug, needs-review

#2818 Store the beforeComplete flag before re-attaching after an ad
  src/js/controller/instream-adapter.js
Labels: bug, needs-review

#2813 Reintroduce qualityLabel so that the html5 provider persists quality
  src/js/api/core-shim.js
  src/js/controller/model.js
  test/unit/program-controller-test.js
Labels: bug, needs-review

#2823 Merge v8.2.x into master
  .gitignore
  docs/api/global.html
  package.json
  src/js/api/core-loader.js
  src/js/api/setup-steps.js
  src/js/controller/controller.js
  src/js/controller/instream-adapter.js
  src/js/controller/model.js
  src/js/playlist/item.js
  src/js/playlist/playlist.js
  src/js/program/media-controller.js
  src/js/program/program-controller.js
  src/js/program/program-listeners.js
  src/js/providers/default.js
  src/js/providers/html5.js
  src/js/providers/video-actions-mixin.js
  src/js/providers/video-listener-mixin.js
  src/js/view/captionsrenderer.js
  src/js/view/constants.js
  src/js/view/controls/components/slider.js
  src/js/view/controls/components/timeslider.js
  src/js/view/controls/controlbar.js
  src/js/view/controls/controls.js
  test/unit/playlist-filtering-test.js
  webpack.config.js
Labels: needs-review

#2824 Use the view-model's "streamType"
  src/js/view/view.js
Labels: needs-review

#2825 Don't background load for live and DVR streams
  src/js/controller/controller.js
Labels: needs-review

#2822 Don't background load for live and DVR streams
  src/js/controller/controller.js
Labels: needs-review

#2831 Add "defaultBandwidthEstimate" property to config
  src/js/api/config.js
Labels: bug

#2832 Add guard check for visualQuality Event
  src/js/program/media-controller.js
  src/js/program/program-listeners.js
Labels: bug, needs-review

#2835 Open Right Click Menu on Long Press
  src/js/utils/ui.js
  src/js/view/controls/controls.js
  src/js/view/controls/rightclick.js
  src/js/view/view.js
Labels: needs-review

#2836 Merge v8.2.3 changes in development
  package.json
Labels: needs-review

#2837 Show which rendition is being used when quality is set to "auto"
  src/css/controls/imports/settings-menu.less
  src/js/view/controls/components/settings/submenu.js
  src/js/view/controls/settings-menu.js
  src/js/view/utils/submenu-factory.js
Labels: enhancement, needs-review

#2839 Don't hide right click menu on tap
  src/js/view/controls/rightclick.js
Labels: needs-review

#2841 Mute button is only set on mobile.
  src/js/view/controls/controls.js
Labels: needs-review

#2844 Implement info overlay
  src/css/controls.less
  src/css/controls/imports/info-overlay.less
  src/css/controls/imports/nextup.less
  src/css/controls/imports/rightclick.less
  src/css/controls/imports/settings-menu.less
  src/css/shared-imports/mixins.less
  src/js/api/config.js
  src/js/view/controls/components/settings/menu.js
  src/js/view/controls/controls.js
  src/js/view/controls/info-overlay.js
  src/js/view/controls/rightclick.js
  src/js/view/controls/templates/info-overlay.js
  src/js/view/controls/templates/rightclick.js
  src/js/view/view.js
Labels: enhancement, needs-review

#2848 Reset beforeComplete on stop
  src/js/program/media-controller.js
  test/unit/background-loading-test.js
Labels: needs-review

#2845 Remove quality indication label if level clicked has the same quality as auto
  src/css/controls/imports/settings-menu.less
  src/js/view/controls/settings-menu.js
Labels: bug, needs-review

#2850 Remove check for manual and adjust styling for quality label
  src/css/controls/imports/settings-menu.less
  src/js/view/controls/settings-menu.js
Labels: needs-review

#2851 Refine sizing for right-click info overlay
  src/css/controls/imports/info-overlay.less
  src/js/view/controls/templates/info-overlay.js
Labels: enhancement, needs-review

#2853 Add coverage for jwplayer._ interface
  test/data/api-underscore-keys.js
  test/unit/api-test.js
  test/unit/dom-test.js
Labels: needs-review

#2852 Fix quality label being displayed in html5 provider
  src/js/view/controls/settings-menu.js
  src/js/view/utils/submenu-factory.js
Labels: bug, needs-review

#2854 Read title/description off of playlistImem, update handling of duration based on streamType
  src/js/view/controls/info-overlay.js
Labels: bug, needs-review

#2855 Check if "levels" exist in "changeAutoLabel"
  src/js/view/controls/settings-menu.js
Labels: bug, needs-review

#2857 [ADS-1074] Trigger mute on autostartMuted change.
  src/js/controller/controller.js
Labels: needs-review

#2864 Fullscreen overlay at bp 2
  src/css/controls/imports/info-overlay.less
Labels: bug, needs-review

#2861 Delete item.starttime on playback complete
  src/js/program/media-controller.js
  test/unit/background-loading-test.js
Labels: bug, needs-review

#2862 Close right click menu on tap (Android Chrome)
  src/js/view/controls/rightclick.js
Labels: needs-review

#2866 Do not show duration in the info overlay if duration is unknown
  src/js/view/controls/info-overlay.js
Labels: needs-review

#2865 Support requestFilter and xhr options in ajax utils
  src/js/utils/ajax.js
  test/unit/ajax-test.js
Labels: needs-review

#2870 Clear blob sources when priming for android
  src/js/program/media-element-pool.js
Labels: bug, needs-review

#2867 [WIP] Add PlayerError class and miscellaneous setup error codes
  src/js/api/Setup.js
  src/js/api/errors.js
Labels: needs-review

#2871 Implement standardized errors for webpack module loading
  src/js/api/core-loader.js
  src/js/api/errors.js
  src/js/controller/controls-loader.js
  src/js/controller/tracks-loader.js
  src/js/providers/providers.js
  src/js/view/captionsrenderer.js
  test/unit/errors/core-loader-error-tests.js
Labels: enhancement, needs-review

#2849 Export Individual Underscore
  src/js/api/config.js
  src/js/api/errors.js
  src/js/api/set-config.js
  src/js/controller/controller.js
  src/js/controller/instream-adapter.js
  src/js/controller/model.js
  src/js/environment/environment.js
  src/js/program/program-listeners.js
  src/js/providers/bandwidth-monitor.js
  src/js/providers/html5.js
  src/js/providers/providers-register.js
  src/js/providers/tracks-mixin.js
  src/js/providers/utils/quality-labels.js
  src/js/utils/dom.js
  src/js/utils/helpers.js
  src/js/utils/language.js
  src/js/utils/parser.js
  src/js/utils/strings.js
  src/js/utils/underscore.js
  src/js/view/captionsrenderer.js
  src/js/view/controls/components/thumbnails.mixin.js
  src/js/view/controls/components/timeslider.js
  src/js/view/controls/controlbar.js
  src/js/view/view.js
  test/unit/jwplayer-selectplayer-test.js
  test/unit/underscore-test.js
Labels: needs-review

#2872 Fix setup tests and update playlist in setup after filtering
  karma.conf.js
  src/js/api/setup-steps.js
  test/index.js
  test/unit/setup-test.js
  webpack.config.js
Labels: needs-review

#2876 Maintain "allSources" when re-filtering playlists
  src/js/playlist/playlist.js
  test/unit/setup-test.js
Labels: needs-review

#2877 Delete mediaElement.src instead of setting it to an empty string
  src/js/program/media-element-pool.js
Labels: bug, needs-review

#2878 Don't assign setup core js error code to non-essential webpack modules
  src/js/api/core-loader.js
Labels: needs-review
