Repository jwplayer/jwplayer, pull requests merged in 2018-09, with the labels that each got.

#3037 Always render the cues gathered from the current positon
  src/js/view/captionsrenderer.js
  test/unit/captionsrenderer-test.js
Labels: bug

#3042 Prevent phone from going to fullscreen on Orientation change on audio mode and chromless players
  src/js/view/utils/views-manager.js
Labels: bug, needs-review

#3050 Use native font scaling when in iOS fullscreen
  src/js/view/captionsrenderer.js
Labels: bug

#3055 Delete captions submenu & button on playlistItem change
  src/js/view/controls/settings-menu.js
Labels: bug

#3036 Implement article matching mvp
  src/js/api/core-shim.js
  test/unit/setup-test.js
Labels: enhancement

#3063 Improve readability for different settings menu states
  src/css/controls/imports/settings-menu.less
  src/js/view/utils/skin.js
Labels: enhancement

#3038 Trigger share menu on right click
  src/css/controls/imports/rightclick.less
  src/js/api/config.js
  src/js/view/controls/components/settings/menu.js
  src/js/view/controls/controls.js
  src/js/view/controls/rightclick.js
  src/js/view/controls/templates/rightclick.js
Labels: needs-review

#3060 Get player language
  src/js/utils/language.js
  test/unit/language-test.js
Labels: needs-review

#2999 Support new google cast button
  src/css/controls/imports/controlbar.less
  src/css/shared-imports/mixins.less
  src/js/view/controls/controlbar.js
  src/js/view/utils/skin.js
Labels: google-chromecast

#3026 Create displayPlaybackLabel config option
  src/css/controls.less
  src/css/controls/imports/idle-variants.less
  src/css/controls/imports/playback-label.less
  src/js/api/config.js
  src/js/view/controls/play-display-icon.js
  test/data/model-properties.js
  test/unit/play-display-icon-test.js
Labels: needs-review

#3077 Update translation files with "playback" property
  src/assets/translations/ar.json
  src/assets/translations/da.json
  src/assets/translations/de.json
  src/assets/translations/es.json
  src/assets/translations/fr.json
  src/assets/translations/it.json
  src/assets/translations/ja.json
  src/assets/translations/nb.json
  src/assets/translations/nl.json
  src/assets/translations/pt.json
  src/assets/translations/ro.json
  src/assets/translations/sv.json
  src/assets/translations/tr.json
  src/assets/translations/zh.json
Labels: needs-review

#3076 New localization options
  src/js/api/config.js
  src/js/view/controls/components/settings/menu.js
  src/js/view/controls/components/timeslider.js
  src/js/view/controls/components/volumetooltip.js
  src/js/view/controls/controlbar.js
  src/js/view/controls/controls.js
  src/js/view/controls/info-overlay.js
  src/js/view/controls/nextuptooltip.js
  src/js/view/controls/rightclick.js
  src/js/view/controls/settings-menu.js
  src/js/view/utils/submenu-factory.js
Labels: needs-review

#3083 Remove/Update hard coded aria labels
  src/js/api/config.js
  src/js/view/controls/templates/rightclick.js
  src/js/view/logo.js
Labels: enhancement

#3086 Delete warning key
  src/js/api/core-shim.js
Labels: bug
