Repository jwplayer/jwplayer, pull requests merged in 2019-02, with the labels that each got.

#3262 Change floatOnScroll boolean to float object
  src/js/view/view.js
Labels: needs-review

#3275 [JW8-2319] Update to webpack 4.29 and babel 7
  Gruntfile.js
  browserslist
  build.version.js
  karma.conf.js
  package.json
  src/assets/translations/en.js
  src/js/api/core-shim.js
  src/js/controller/model.js
  src/js/model/simplemodel.js
  src/js/polyfills/webvtt.js
  src/js/program/media-controller.js
  src/js/program/program-controller.js
  src/js/templates/error.js
  src/js/templates/floating-close-button.js
  src/js/templates/logo.js
  src/js/templates/player.js
  src/js/utils/backbone.events.js
  src/js/utils/eventable.js
  src/js/utils/ui.js
  src/js/view/controls/play-display-icon.js
  src/js/view/view-model.js
  test/data/api-members.js
  test/mock/mock-model.js
  test/unit/captionsrenderer-test.js
  test/unit/controlbar-test.js
  test/unit/controls/settings-menu-test.js
  test/unit/model-qoe-test.js
  test/unit/play-display-icon-test.js
  test/unit/plugins-test.js
  test/unit/program-controller-test.js
  test/unit/simplemodel-test.js
  test/unit/storage-test.js
  webpack.config.js
  yarn.lock
Labels: needs-review

#3276 Fix regression from floating changes
  src/js/view/view.js
Labels: bug, needs-review

#3278 Rename internal 'floating' model variable
  src/js/view/utils/visibility.js
  src/js/view/view.js
Labels: needs-review

#3250 [JW8-2159]Toggle settings menu icon dependent on amount of submenus
  src/js/view/controls/components/settings/menu.js
  src/js/view/controls/settings-menu.js
Labels: enhancement, needs-review

#3280 [JW8-2595] Return in getElementWindow() if element is null
  src/js/utils/ui.js
Labels: needs-review

#3289 JW8-2662 Captions not on by default if not muted
  src/js/controller/captions.js
  src/js/controller/controller.js
Labels: needs-review

#3282 Autopause Refinements
  src/js/api/config.js
  src/js/controller/controller.js
  src/js/program/program-controller.js
  test/data/model-properties.js
Labels: needs-review

#3295 [JW8-2504] Stop video on noResume.
  src/js/controller/controller.js
Labels: needs-review
