Repository jwplayer/jwplayer, pull requests merged in 2019-03, with the labels that each got.

#3267 [JW8-2530] [JW8-5612] Update float on scroll resizing on mobile and desktop
  src/css/controls/imports/settings-menu.less
  src/css/jwplayer/flags/floatingplayer.less
  src/css/shared-imports/vars.less
  src/js/controller/controller.js
  src/js/templates/floating-close-button.js
  src/js/view/controls/controls.js
  src/js/view/utils/views-manager.js
  src/js/view/view.js
Labels: enhancement, needs-review

#3283 [JW8-2506]Retain pause state when/after seeking
  src/js/controller/controller.js
  src/js/view/controls/controlbar.js
Labels: enhancement, needs-review

#3281 JW8-2183 Audio mode horizontal volume slider
  src/css/controls/flags/audioplayer.less
  src/css/controls/imports/slider.less
  src/js/view/controls/components/timeslider.js
  src/js/view/controls/components/tooltipicon.js
  src/js/view/controls/components/volumetooltip.js
  src/js/view/controls/components/volumetooltipicon.js
  src/js/view/controls/controlbar.js
  src/js/view/controls/controls.js
Labels: needs-review

#3309 [JW8-2627] Do not allow dragging ads on floating player
  src/js/view/floating-drag-ui.js
  src/js/view/view.js
Labels: enhancement

#3318 [JW8-5644] Fix audio only live player ui
  src/css/controls/flags/audioplayer.less
Labels: bug

#3320 [JW8-5643] Limit prevent scrolling to mobile
  src/js/view/floating-drag-ui.js
Labels: enhancement

#3324 About This Video' right click option doesn't work on mobile JW8-5632
  src/css/controls/imports/shortcuts-tooltip.less
  src/js/view/controls/rightclick.js
  src/js/view/controls/shortcuts-tooltip.js
  src/js/view/controls/templates/shortcuts-tooltip.js
Labels: bug

#3336 Update the player state to "paused" after seeking...
  src/js/program/program-listeners.js
Labels: adds-tech-debt
