Repository jwplayer/jwplayer, pull requests merged in 2019-01, with the labels that each got.

#3236 [JW8-2408] Close settings menu if visible when changing playlist item
  src/js/view/controls/settings-menu.js
Labels: bug

#3243 Make controls visible on focus when ad is playing
  src/js/view/controls/controls.js
Labels: enhancement

#3246 Sanitize nested svg elements in svgparser.js
  src/js/utils/dom.js
  src/js/utils/svgParser.js
  test/unit/replace-inner-html-test.js
  test/unit/sanitize-html-test.js
Labels: bug

#3252 Set Chromecast item startTime to currentTime to support DVR live edge
  src/js/program/program-controller.js
Labels: needs-review

#3254 Don't expect seekRange to be defined on the player model
  src/js/view/controls/components/timeslider.js
Labels: needs-review

#3256 Unshift cues so that they are added in order
  src/js/providers/tracks-mixin.js
Labels: needs-review

#3258 Prevent exception exiting fullscreen via escape key
  src/js/view/controls/controls.js
  src/js/view/utils/request-fullscreen-helper.js
Labels: bug, needs-review

#3249 Parse HTML for titles and localization
  src/js/view/controls/components/simple-tooltip.js
  src/js/view/controls/info-overlay.js
  src/js/view/controls/play-display-icon.js
Labels: enhancement, needs-review

#3257 Fix DVR seeking in html5 provider
  src/js/providers/html5.js
  src/js/view/controls/controlbar.js
Labels: needs-review

#3260 Prevent other svg icons from animating when displayPlaybackLabel is on
  src/css/controls/states.less
Labels: bug, needs-review

#3259 [JW8-2607] Keep controls visible is activated via keyboard
  src/js/view/controls/controls.js
Labels: bug, needs-review

#3261 [JW8-2566] Support legacy config options in translated localization block
  src/js/api/config.js
  src/js/api/setup-steps.js
  src/js/utils/language.js
  test/unit/language-test.js
Labels: needs-review

#3264 [JW8-2594] Support seeking in DVR using currentTime
  src/js/providers/html5.js
  src/js/view/controls/controlbar.js
Labels: needs-review

#3263 [JW8-1703] Set cast mediaModel currentTime to support resume from DVR casting
  src/js/program/program-controller.js
Labels: needs-review

#3271 [JW8-2349][JW8-2350] Update test dependencies
  package.json
  test/unit/api-get-config-test.js
  test/unit/api-test.js
  test/unit/controls/settings-menu-test.js
  test/unit/core-shim-test.js
  test/unit/language-test.js
  test/unit/program-controller-test.js
  test/unit/sanitize-html-test.js
  test/unit/setup-steps-test.js
  test/unit/setup-test.js
  test/unit/ui-test.js
  yarn.lock
Labels: enhancement, needs-review

#3272 Enable captions on autostart muted with config
  src/js/controller/captions.js
  src/js/controller/controller.js
Labels: needs-review

#3274 Merge v8.7.x branch to master
  package.json
  src/js/controller/captions.js
  src/js/controller/controller.js
Labels: needs-review
